### ISSUE TITLE
Page resources missing for topic Text classification using NLTK

### ISSUE THREAD

**Issue by datNurd** [bbengfort/bbengfort.github.io#5]
Hello,
All the page styling resources like css, fonts, images are missing (returning 404) due to which the page is not rendering as it should. The following is the page link http://bbengfort.github.io/tutorials/2016/05/19/text-classification-nltk-sckit-learn.html

**Comment by bbengfort** [comment]
Thanks - looks like something was going on with the `baseurl` in the config -- it worked locally but not when built with GitHub pages. I just changed the `baseurl` to an absolute url and enforced https; seems to be working now.
